# [Choice] https://github.com/KEINOS/VSCode-Dev-Container-Go/pkgs/container/vscode-dev-container-go
ARG VARIANT="latest"
FROM ghcr.io/keinos/vscode-dev-container-go:${VARIANT}

# [Optional] Uncomment this section to install additional OS packages. Do not forget to set back the
#            user to "vscode".
# USER root
# RUN apt add --no-cache <your-package-list-here>

# [Optional] Uncomment this section to use go get to install anything else you need.
# USER vscode
# RUN cd /tmp && go install <your-dependency-or-tool>
