name: All Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  coverage:
    name: Unit test and coverage
    environment: TOKENS_BY_KEINOS

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Download Modules
        run: go mod download

      - name: Install ShellCheck
        run: |
          url_download="https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.$(uname -m).tar.xz"
          timestamp="$(date +%Y%m%d%H%M%S)"
          path_tmp_dir=$(mktemp "/tmp/${NameRepo}-${timestamp}.tmp.XXXXXX")
          echo "TEMP PATH: ${path_tmp_dir}"
          wget -P "${path_tmp_dir}/" "$url_download"
          tar xvf "${path_tmp_dir}"/shellcheck* -C "${path_tmp_dir}/"
          sudo cp "${path_tmp_dir}/shellcheck-latest/shellcheck" "$(dirname $(which tar))/shellcheck"
          shellcheck --version

      - name: Install shfmt
        run: |
          GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt

      - name: Install go-carpet
        run: |
          GO111MODULE=on go get github.com/msoap/go-carpet

      - name: Install gomarkdoc
        run: |
          GO111MODULE=on go get github.com/princjef/gomarkdoc/cmd/gomarkdoc

      - name: Run gofmt
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-path: '.'
          gofmt-flags: '-d -e' # display diffs and report all errors

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)/bin"
          golangci-lint --version

      - name: Run coverage (Linux)
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        if: runner.os != 'Windows'
        run: |
          go mod tidy
          ./.github/run-tests-merge.sh
