# =============================================================================
#  Release Assets and Homebrew's Tap
# =============================================================================
# This workflow will build the binaries and push the archives to the assets in
# the releases page if a release was created. Then pushes the tap config file
# for Homebrew tap. See: ../../.goreleaser.yml
name: Release

on:
  workflow_dispatch:
  release:
    types:
      - created
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Update os packages
        run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get -y upgrade
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1'
          check-latest: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
